from __future__ import annotations


TEXT_REPLACEMENTS_RU = {
    "Paper Edge Discovery": "Поиск преимущества на Paper",
    "Paper Runtime Sample Collection Daily Summary": "Дневная сводка накопления выборки Paper Runtime",
    "Paper Runtime Sample Collection Operations": "Операции накопления выборки Paper Runtime",
    "Paper Sample Operations Timer Health": "Здоровье таймера операций выборки",
    "Paper Sample Accumulation Monitor": "Монитор накопления выборки",
    "Paper Sample Collection Timer Health": "Здоровье таймера накопления выборки",
    "Paper Runtime Sample Collection Phase Close": "Закрытие фазы накопления выборки",
    "Phase II Paper Edge Discovery Summary": "Итоги Phase II: поиск преимущества",
    "MarketCore UI Systemd Health": "Здоровье MarketCore UI и systemd",

    "Candidate Explainability": "Объяснение кандидатов",
    "TOP Candidates Detail": "Детализация TOP-кандидатов",
    "Research Candidates": "Кандидаты исследования",
    "Paper Runtime Real Data": "Реальные данные Paper Runtime",
    "Knowledge Graph": "Граф знаний",
    "Validation": "Валидация",
    "Edge Validation Queue": "Очередь проверки преимущества",
    "Edge Validation Pipeline": "Pipeline проверки преимущества",
    "Edge Robustness Check": "Проверка устойчивости преимущества",
    "Edge OOS Validation": "Вневыборочная проверка преимущества",
    "Edge OOS Backtest": "Вневыборочный бэктест преимущества",
    "Micro Live Readiness": "Готовность Micro Live",

    "Sample Collection Summary": "Сводка накопления выборки",
    "Closest Candidates To Recheck": "Ближайшие кандидаты к повторной проверке",
    "Timer Details": "Детали таймера",
    "Operations Timer Details": "Детали таймера операций",
    "Systemd Details": "Детали systemd",
    "Phase Close Summary": "Сводка закрытия фазы",
    "Pipeline Row Coverage": "Покрытие строк pipeline",
    "Daily Summary": "Дневная сводка",
    "Operations Queue": "Очередь операций",
    "Readiness Gate": "Шлюз готовности",
    "OOS Backtest": "Вневыборочный бэктест",
    "OOS Validation": "Вневыборочная проверка",
    "Robustness Check": "Проверка устойчивости",
    "Accumulation": "Накопление",
    "Summary": "Сводка",
    "Safety": "Безопасность",
    "Result": "Результат",
    "Next Action": "Следующее действие",
    "Source:": "Источник:",
    "Источник:": "Источник:",

    "Platform M2": "Платформа M2",
    "MarketCore OS": "MarketCore OS",
    "MarketCore UI Shell": "Оболочка MarketCore UI",
    "Единая оболочка платформы": "Единая оболочка платформы",

    "Settings": "Настройки",
    "Risk": "Риски",
    "Risks": "Риски",
    "Orders": "Заявки",
    "Portfolio": "Портфель",
    "Research": "Исследования",
    "Logs": "Журнал",
    "System": "Система",
    "Statistics": "Статистика",
    "Health": "Здоровье",
    "Queue": "Очередь",
    "Operations": "Операции",
    "Status": "Статус",
    "Priority": "Приоритет",
    "Ready": "Готово",
    "Blocked": "Заблокировано",
    "Failed": "Ошибка",
    "Rejected": "Отклонено",
    "Watchlist": "Наблюдение",
    "Collecting": "Накопление",
    "Wait Sample": "Ожидание выборки",
    "Wait Both": "Ожидание двух выборок",
    "Wait Total": "Ожидание общей выборки",
    "Wait OOS": "Ожидание OOS-выборки",
    "Need Total": "Нужно общих сделок",
    "Need OOS": "Нужно OOS-сделок",
    "Total Trades": "Всего сделок",
    "OOS Trades": "OOS-сделки",
    "Progress": "Прогресс",
    "Action": "Действие",
    "Reason": "Причина",
    "Conclusion": "Вывод",
    "Recommended Action": "Рекомендованное действие",
    "Open URL": "URL открытия",
    "Risk URL": "URL рисков",
    "Settings URL": "URL настроек",
    "Refreshed At": "Обновлено",
    "Source": "Источник",

    "P&L Total": "P&L всего",
    "P&amp;L Total": "P&L всего",
    "Signals Today": "Сигналы сегодня",
    "Closed Trades": "Закрытые сделки",
    "Timer Active State": "Активное состояние таймера",
    "Timer Unit File State": "Состояние unit-файла таймера",
    "Service Result": "Результат сервиса",
    "Service Healthy": "Сервис исправен",
    "Timer Healthy": "Таймер исправен",
    "Home HTTP OK": "Home HTTP OK",
    "Risk HTTP OK": "Risk HTTP OK",
    "Settings HTTP OK": "Settings HTTP OK",
    "Micro Live Allowed": "Micro Live разрешён",
    "Micro Live Ready Rows": "Строк готовности Micro Live",
    "Micro Live Allowed Rows": "Строк разрешения Micro Live",

    "Candidate": "Кандидат",
    "Candidates": "Кандидаты",
    "Evidence": "Доказательства",
    "Weakness": "Слабое место",
    "Block Reason": "Причина блокировки",
    "Operation": "Операция",
    "Pipeline": "Pipeline",
    "Robustness": "Устойчивость",
    "Backtest": "Бэктест",
    "Readiness": "Готовность",
}


def normalize_ui_text(text: str) -> str:
    result = text

    for source, target in sorted(TEXT_REPLACEMENTS_RU.items(), key=lambda item: len(item[0]), reverse=True):
        result = result.replace(source, target)

    return result
