from __future__ import annotations

import psycopg2


MESSAGES = {
    "availability.available": "Доступно",
    "availability.observation_only": "Только наблюдение",
    "availability.unavailable": "Недоступно",
    "capital.metric.available": "Доступные средства",
    "capital.metric.daily_pnl": "Финансовый результат за день",
    "capital.metric.equity": "Стоимость капитала",
    "capital.metric.positions": "Открытые позиции",
    "capital.metric.total_pnl": "Совокупный финансовый результат",
    "capital.value.unavailable": "Нет подтверждённых данных",
    "capital.workspace.subtitle": "Капитал, позиции и финансовый результат",
    "capital.workspace.title": "Капитал",
    "column.active.cohort.id": "Действующая группа наблюдений",
    "column.active.observations": "Наблюдения в действующей группе",
    "column.avg.hold.minutes": "Среднее время удержания, мин",
    "column.correlation.risk.score": "Оценка корреляционного риска",
    "column.count": "Количество",
    "column.coverage.pct": "Покрытие, %",
    "column.daily.loss.risk.score": "Оценка риска дневного убытка",
    "column.delta.expectancy": "Изменение ожидаемого результата",
    "column.delta.profit.factor": "Изменение коэффициента прибыли",
    "column.eligible.closed": "Закрытые сделки, соответствующие условиям",
    "column.eligible.families": "Группы стратегий, соответствующие условиям",
    "column.eligible.family.names": "Стратегии, соответствующие условиям",
    "column.eligible.net.pnl": "Финансовый результат соответствующих сделок",
    "column.evidence.json": "Подтверждающие данные",
    "column.expectancy.bps": "Ожидаемый результат, базисные пункты",
    "column.exploratory.closed": "Закрытые исследовательские сделки",
    "column.exploratory.families": "Исследовательские группы стратегий",
    "column.exploratory.family.names": "Исследовательские стратегии",
    "column.exploratory.net.pnl": "Финансовый результат исследовательских сделок",
    "column.exposure.risk.score": "Оценка риска экспозиции",
    "column.factory.status": "Состояние исследовательского контура",
    "column.family.code": "Код группы стратегий",
    "column.folds.passed": "Пройденные временные отрезки проверки",
    "column.folds.total": "Всего временных отрезков проверки",
    "column.guard.check.status": "Результат контрольной проверки",
    "column.guard.created.at": "Время контрольной проверки",
    "column.guard.cron.ready": "Готовность планировщика заданий",
    "column.guard.disk.used.pct": "Использование диска, %",
    "column.guard.memory.available.mb": "Доступная память, МБ",
    "column.guard.reasons.json": "Причины ограничений",
    "column.guard.websocket.connected": "Подключение к потоку котировок",
    "column.guard.worker.log.ready": "Готовность журнала обработчика",
    "column.latest.age.hours": "Возраст последних данных, ч",
    "column.linkage.pct": "Доля связанных записей, %",
    "column.linked.fills": "Связанные исполнения",
    "column.market.data.quality": "Качество рыночных данных",
    "column.market.data.status": "Состояние рыночных данных",
    "column.minimum.closed": "Требуемое число закрытых сделок",
    "column.minimum.sessions": "Требуемое число торговых сессий",
    "column.missing.closed": "Недостающие закрытые сделки",
    "column.missing.sessions": "Недостающие торговые сессии",
    "column.net.pnl": "Чистый финансовый результат",
    "column.oos.expectancy": "Ожидаемый результат вневыборочной проверки",
    "column.oos.profit.factor": "Коэффициент прибыли вневыборочной проверки",
    "column.oos.trades": "Сделки вневыборочной проверки",
    "column.open": "Открытые",
    "column.parameter.json": "Параметры варианта",
    "column.pass.rate.pct": "Доля успешно пройденных проверок, %",
    "column.pending": "Ожидают обработки",
    "column.policy.code": "Правило управления позицией",
    "column.position.risk.score": "Оценка риска позиции",
    "column.positions.closed": "Закрытые позиции",
    "column.positions.opened": "Открытые позиции",
    "column.profit.factor": "Коэффициент прибыли",
    "column.profit.locks": "Фиксации прибыли",
    "column.promotion.allowed": "Допуск к следующему этапу",
    "column.quality.pending.closed": "Закрытые сделки, ожидающие проверки качества",
    "column.quality.pending.families": "Группы стратегий, ожидающие проверки качества",
    "column.quality.pending.family.names": "Стратегии, ожидающие проверки качества",
    "column.quality.pending.net.pnl": "Финансовый результат сделок, ожидающих проверки качества",
    "column.quotes.verified": "Котировки подтверждены",
    "column.ready.for.paper": "Готовность к модельным сделкам",
    "column.reason.code": "Код причины",
    "column.reason.codes": "Коды причин",
    "column.reason.column": "Проверяемый показатель",
    "column.reason.value": "Значение причины",
    "column.recommendation.code": "Код рекомендации",
    "column.refreshed.at": "Время обновления",
    "column.regime.code": "Код рыночного режима",
    "column.regime.coverage.ratio": "Покрытие рыночными режимами",
    "column.regime.group": "Группа рыночных режимов",
    "column.reporting.cohort.id": "Отчётная группа наблюдений",
    "column.reporting.is.archived": "Отчётная группа архивирована",
    "column.risk.decision.code": "Решение контура риска",
    "column.risk.score": "Оценка риска",
    "column.rows.total": "Всего записей",
    "column.session.code": "Торговая сессия",
    "column.sessions": "Торговые сессии",
    "column.signal.ts": "Время сигнала",
    "column.source.table": "Источник данных",
    "column.stage.code": "Этап проверки",
    "column.stops.improved": "Улучшенные защитные стоп-приказы",
    "column.stops.placed": "Установленные защитные стоп-приказы",
    "column.strategy.code": "Код стратегии",
    "column.strategy.family": "Группа стратегий",
    "column.take.profits": "Срабатывания фиксации прибыли",
    "column.target": "Целевое значение",
    "column.total": "Всего",
    "column.trading.days": "Торговые дни",
    "column.trailing.active": "Позиции с динамической защитой",
    "column.trailing.closed": "Закрытые позиции с динамической защитой",
    "column.trailing.exits": "Выходы по динамической защите",
    "column.trailing.net.pnl": "Финансовый результат динамической защиты",
    "column.trailing.open": "Открытые позиции с динамической защитой",
    "column.trailing.total": "Всего позиций с динамической защитой",
    "column.trailing.unsafe": "Позиции с нарушением динамической защиты",
    "column.unsafe": "С нарушением защиты",
    "column.variants": "Варианты параметров",
    "column.verdict.code": "Итог проверки",
    "freshness.as_of_reported": "Актуальность указана источником",
    "freshness.as_of_unavailable": "Время актуальности неизвестно",
    "freshness.current": "Актуальные данные",
    "freshness.stale": "Устаревшие данные",
    "home.control_center.edge_metric": "Данные готовы: {ready} из {total}; вневыборочную проверку прошли: {passed}",
    "home.profit_factory.decision.no_verified_data": "Нет подтверждённых данных для решения",
    "home.traffic.data.value": "Готовы {ready} из {total} источников данных",
    "home.traffic.edge.value": "Вневыборочную проверку прошли: {passed}",
    "home.traffic.execution.unverified": "Цены покупки и продажи, а также биржевой стакан не подтверждены",
    "home.traffic.forward.value": "Проверка на последующих данных: {candidates} кандидатов, {observations} наблюдений",
    "home.traffic.live.blocked": "Продвижение к реальным торгам запрещено",
    "intraday.metric.instruments": "Инструменты",
    "intraday.metric.last_trade": "Последняя сделка",
    "intraday.metric.paper_fills": "Исполненные модельные сделки",
    "intraday.metric.paper_pnl": "Финансовый результат модельных сделок",
    "intraday.metric.paper_signals": "Сигналы модельных сделок",
    "intraday.metric.paper_status": "Состояние модельного режима",
    "intraday.metric.pnl": "Финансовый результат",
    "intraday.metric.shadow_fills": "Исполненные теневые сделки",
    "intraday.metric.shadow_last_event": "Последнее событие теневого режима",
    "intraday.metric.shadow_orders": "Заявки теневого режима",
    "intraday.metric.shadow_positions": "Позиции теневого режима",
    "intraday.metric.trades": "Сделки",
    "intraday.section.live.title": "Реальные торги",
    "intraday.section.paper.title": "Модельные сделки",
    "intraday.section.shadow.title": "Теневые сделки",
    "intraday.workspace.subtitle": "Сделки, позиции и качество внутридневного исполнения",
    "intraday.workspace.title": "Внутридневная торговля",
    "paper.action.request_observation": "Запустить наблюдение модельных сделок",
    "program.metric.marketcore_status": "Состояние MarketCore",
    "program.metric.micro_live_allowed": "Допуск к ограниченным реальным торгам",
    "program.metric.paper_status": "Состояние модельного режима",
    "program.metric.platform_status": "Состояние платформы",
    "program.metric.quarter": "Текущий квартал",
    "program.metric.readiness_ready": "Готовые проверки",
    "program.metric.readiness_total": "Всего проверок готовности",
    "program.metric.research_status": "Состояние исследований",
    "program.metric.top3_status": "Состояние трёх приоритетных стратегий",
    "program.section.readiness.title": "Готовность к ограниченным реальным торгам",
    "program.section.summary.title": "Сводное состояние программы",
    "program.workspace.subtitle": "Этапы развития и готовность торгового контура",
    "program.workspace.title": "Программа развития",
    "quality.configuration_validated": "Настройки проверены",
    "quality.mixed_freshness": "Данные разной актуальности",
    "quality.no_verified_kpi": "Нет подтверждённых ключевых показателей",
    "quality.source_as_of_unavailable": "Источник не сообщил время актуальности",
    "quality.stale": "Данные устарели",
    "quality.verified": "Данные проверены",
    "research.action.request_refresh": "Обновить исследовательские данные",
    "research.control.section.block.title": "Блокирующие ограничения",
    "research.control.section.entry.title": "Условия входа",
    "research.control.section.execution.title": "Качество исполнения",
    "research.control.section.execution_variants.title": "Варианты исполнения",
    "research.control.section.exit.title": "Условия выхода",
    "research.control.section.funnel.title": "Воронка проверки сигналов",
    "research.control.section.loss_reasons.title": "Причины отрицательного результата",
    "research.control.section.market.title": "Рыночные условия",
    "research.control.section.relationships.title": "Связи между инструментами",
    "research.control.section.risk.title": "Ограничения риска",
    "research.control.section.shadow.title": "Теневые сделки",
    "research.control.section.shadow_requirements.title": "Требования к теневому наблюдению",
    "research.control.section.volatility.title": "Режимы волатильности",
    "research.control.traffic.data.title": "Исходные данные",
    "research.control.traffic.data.value": "Готовы {ready} из {total} источников",
    "research.control.traffic.edge.title": "Вневыборочная проверка",
    "research.control.traffic.edge.value": "Проверку прошли: {passed}",
    "research.control.traffic.live.blocked": "Продвижение к реальным торгам запрещено",
    "research.control.traffic.live.title": "Реальные торги",
    "research.control.traffic.quotes.title": "Качество котировок",
    "research.control.traffic.quotes.value": "Подтверждено источников котировок: {verified}",
    "research.control.traffic.watch.title": "Наблюдение",
    "research.control.traffic.watch.value": "Кандидатов: {candidates}; наблюдений: {observations}",
    "research.control.workspace.subtitle": "Исследования, вневыборочная проверка и продвижение кандидатов",
    "research.control.workspace.title": "Центр управления исследованиями",
    "research.metric.active_symbols": "Активные инструменты",
    "research.metric.candidates": "Кандидаты",
    "research.metric.failed_symbols": "Инструменты с ошибками",
    "research.metric.oos_pass": "Прошли вневыборочную проверку",
    "research.metric.oos_total": "Всего вневыборочных проверок",
    "research.metric.paper_ready": "Готовы к модельным сделкам",
    "research.metric.queue_failed": "Запросы с ошибкой",
    "research.metric.queue_pending": "Запросы в ожидании",
    "research.metric.queue_total": "Всего запросов",
    "research.metric.summary_oos_pass": "Подтверждённые вневыборочной проверкой",
    "research.metric.supervisor_status": "Состояние управляющего обработчика",
    "research.workspace.subtitle": "Кандидаты, проверки и готовность к модельным сделкам",
    "research.workspace.title": "Исследования",
    "risk.column.cluster": "Группа коррелирующих позиций",
    "risk.column.heat": "Нагрузка на лимит риска",
    "risk.column.portfolio_share": "Доля портфеля",
    "risk.column.positions": "Позиции",
    "risk.column.state": "Состояние риска",
    "risk.metric.available_risk": "Доступный резерв риска",
    "risk.metric.daily_risk": "Использованный дневной риск",
    "risk.metric.decisions_blocked": "Заблокированные решения",
    "risk.metric.decisions_total": "Всего решений",
    "risk.metric.drawdown": "Просадка",
    "risk.metric.execution_allowed": "Допуск к исполнению",
    "risk.metric.micro_live_allowed": "Допуск к ограниченным реальным торгам",
    "risk.metric.risk_budget": "Лимит риска",
    "risk.metric.risk_score": "Совокупная оценка риска",
    "risk.metric.runtime_allowed": "Допуск исполняющего контура",
    "risk.value.unavailable": "Нет подтверждённых данных",
    "risk.workspace.subtitle": "Лимиты, экспозиция, просадка и решения контура риска",
    "risk.workspace.title": "Риск",
    "settings.field.broker": "Брокер",
    "settings.field.currency": "Валюта отчётности",
    "settings.field.locale": "Язык интерфейса",
    "settings.field.timezone": "Часовой пояс",
    "settings.workspace.subtitle": "Язык, время, валюта и источник брокерских данных",
    "settings.workspace.title": "Настройки",
    "status.elevated": "Повышенный риск",
    "status.normal": "Нормальное состояние",
    "status.ok": "Без нарушений",
    "home.card.edge.title": "Статистическое преимущество · вневыборочная проверка",
    "home.profit_factory.roi": "Фактическая рентабельность капитала",
    "portfolio.column.p&l %": "Финансовый результат, %",
    "portfolio.column.p&l за день": "Финансовый результат за день",
    "portfolio.column.p&l общий": "Совокупный финансовый результат",
}


def main() -> None:
    with psycopg2.connect("postgresql:///finam_core") as connection:
        with connection.cursor() as cursor:
            for resource_key, caption in MESSAGES.items():
                group = resource_key.split(".", 1)[0]
                cursor.execute(
                    """
                    INSERT INTO presentation.ui_resource_v1 (
                        resource_key,locale_code,caption,caption_short,caption_mobile,tooltip,icon,resource_group
                    ) VALUES (%s,'ru',%s,%s,%s,%s,'',%s)
                    ON CONFLICT(resource_key,locale_code) DO UPDATE SET
                        caption=EXCLUDED.caption,caption_short=EXCLUDED.caption_short,
                        caption_mobile=EXCLUDED.caption_mobile,tooltip=EXCLUDED.tooltip,
                        resource_group=EXCLUDED.resource_group,updated_at=clock_timestamp()
                    """,
                    (resource_key, caption, caption, caption, caption, group),
                )
    print(f"messages_registered={len(MESSAGES)}")
    print("locale=ru-RU")
    print("generated_translations=0")
    print("VERDICT=MARKETCORE_STAGE6_RU_CATALOG_V2_REGISTERED")


if __name__ == "__main__":
    main()
