services:
  grafana:
    image: grafana/grafana:11.0.0
    container_name: finam-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: finam_admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
