from __future__ import annotations

SYMBOL_STRATEGY_MAP = {
    "BRM6@RTSX": "BR_CONSERVATIVE_BREAKOUT",
    "BRN6@RTSX": "BR_CONSERVATIVE_BREAKOUT",
    "NGK6@RTSX": "NG_VOLATILITY_BREAKOUT",
    "USDRUBF@RTSX": "USDRUB_REGIME",

    "LKOH@MISX": "MEAN_REVERSION_EQUITY",
    "SBERP@MISX": "MEAN_REVERSION_EQUITY",
    "NVTK@MISX": "MEAN_REVERSION_EQUITY",
    "VTBR@MISX": "MEAN_REVERSION_EQUITY",
    "X5@MISX": "MEAN_REVERSION_EQUITY",

    "PLZL@MISX": "TREND_PULLBACK_EQUITY",
    "OZON@MISX": "TREND_PULLBACK_EQUITY",
    "SFIN@MISX": "TREND_PULLBACK_EQUITY",
}

DEFAULT_STRATEGY = "MEAN_REVERSION_EQUITY"
