#!/usr/bin/env python3

print("=== MARKET_INDEX_SOURCE_DECISION_V1 ===")
print("mode=decision_only")
print("db_update=0")
print("runtime_changed=0")
print("execution_changed=0")
print("real_trading_enabled=0")
print("orders_sent=0")

print("")
print("DISCOVERY_RESULT")
print("usable_index_sources=5")
print("primary_feature_source=public.feature_snapshots")
print("secondary_price_source=public.market_bars")
print("historical_br_source=public.market_bars_br_m5_rolling_v1")
print("research_feature_source=public.research_feature_store")

print("")
print("INDEX_AVAILABILITY")
print("index=IMOEX status=NOT_FOUND_IN_FEATURE_SNAPSHOTS")
print("index=RTSI status=NOT_FOUND_IN_FEATURE_SNAPSHOTS")
print("index=MOEX status=NOT_FOUND_IN_FEATURE_SNAPSHOTS")
print("index=USD_RUB status=AVAILABLE rows=21217 source=public.feature_snapshots")
print("index=BR status=AVAILABLE rows=27206 source=public.feature_snapshots")
print("index=BRENT status=NOT_FOUND_IN_FEATURE_SNAPSHOTS")

print("")
print("DECISION")
print("decision=USE_AVAILABLE_CONTEXT_FIRST")
print("context_v1=FX_USDRUB")
print("context_v1=ENERGY_BR")
print("defer_context=MOEX_INDEX")
print("defer_context=RTS_INDEX")
print("reason=no_imoex_rtsi_feature_snapshots_found")
print("reason=usd_rub_and_br_have_existing_feature_state_rows")

print("")
print("DESIGN_RULES")
print("rule=index_context_is_optional")
print("rule=do_not_block_market_state_edge_baseline")
print("rule=do_not_mix_index_context_into_instrument_signature_v1")
print("rule=store_context_as_additional_dimension")
print("rule=no_runtime_execution_changes")

print("")
print("NEXT_STEPS")
print("next=MARKET_INDEX_STATE_SCHEMA_PLAN_V1")
print("next=MARKET_INDEX_STATE_CONTEXT_SCORECARD_V1")

print("")
print("VERDICT=MARKET_INDEX_SOURCE_DECISION_READY")
