#!/usr/bin/env python3

print("=== HISTORICAL_TRADE_CANONICAL_SOURCE_DECISION_V1 ===")
print("mode=decision_only")
print("db_update=0")
print("runtime_changed=0")
print("execution_changed=0")
print("real_trading_enabled=0")
print("orders_sent=0")

print("")
print("AUDIT_RESULT")
print("best_source=public.closed_trades")
print("best_rows=4073")
print("has_symbol=1")
print("has_timeframe=1")
print("has_entry_ts=1")
print("has_exit_ts=1")
print("has_net_pnl=1")
print("has_payload=1")
print("first_ts=2026-05-04T15:29:21.089519+00:00")
print("last_ts=2026-06-09T09:32:50.915396+00:00")

print("")
print("SECONDARY_SOURCES")
print("source=public.analytics_strategy_trades_v2 rows=1962 role=cross_check")
print("source=public.closed_trade_chains_v3 rows=397 role=cross_check")
print("source=public.trade_attribution_v3 rows=397 role=cross_check")
print("source=public.trade_outcomes rows=44 role=current_small_sample")

print("")
print("DECISION")
print("canonical_historical_trade_source=public.closed_trades")
print("decision_reason=max_rows_with_required_columns")
print("decision_reason=has_symbol_timeframe_entry_exit_net_pnl")
print("decision_reason=suitable_for_market_state_backfill_expansion")

print("")
print("EXCLUSIONS")
print("exclude=public.closed_trade_chains_v2 reason=needs_time_mapping_or_pnl_mapping")
print("exclude=public.trades reason=fill_level_not_closed_trade_pnl")
print("exclude=public.v_trades_pnl_paired_grafana reason=view_without_symbol_timeframe_entry_ts")
print("exclude=shadow_runtime_tables reason=not_closed_trade_pnl_source")

print("")
print("NEXT_STEPS")
print("next=HISTORICAL_MARKET_STATE_BACKFILL_FOR_CLOSED_TRADES_PLAN_V1")
print("next=HISTORICAL_TRADE_LINKING_TO_MARKET_STATE_V1")

print("")
print("VERDICT=HISTORICAL_TRADE_CANONICAL_SOURCE_DECISION_READY")
