from __future__ import annotations
from marketcore.presentation.render_tree.v2 import RenderContentV2,RenderDocumentV2,RenderNodeStateV2,RenderNodeTypeV2,RenderNodeV2,validate_render_document_v2
from marketcore.presentation.workspace_v2.domain.intraday_snapshot_v2 import IntradaySnapshotV2

def _leaf(t,i,*,key=None,value=None,fmt=None,level=None):return RenderNodeV2(t,i,content=RenderContentV2(message_key=key,value=value,format_code=fmt,level_code=level))
def _metric(prefix,code,value,fmt="INTEGER"):return RenderNodeV2(RenderNodeTypeV2.METRIC_ROW,f"{prefix}.{code}",children=(_leaf(RenderNodeTypeV2.METRIC_LABEL,f"{prefix}.{code}.label",key=f"intraday.metric.{code}"),_leaf(RenderNodeTypeV2.METRIC_VALUE,f"{prefix}.{code}.value",value=value,fmt=fmt)))
def _section(code,state,source_time,source_identity,metrics):return RenderNodeV2(RenderNodeTypeV2.SECTION,f"intraday.section.{code}",state=RenderNodeStateV2(status_code=state,freshness_code="AS_OF_REPORTED" if source_time else "UNAVAILABLE",source_as_of=source_time,source_identity=source_identity if source_time else None),children=(_leaf(RenderNodeTypeV2.TITLE,f"intraday.section.{code}.title",key=f"intraday.section.{code}.title",level="SECTION"),RenderNodeV2(RenderNodeTypeV2.METRIC_LIST,f"intraday.section.{code}.metrics",children=metrics)))

def render_intraday_domain_v2(s:IntradaySnapshotV2,*,timezone_code="Europe/Moscow"):
    intraday=(_metric("intraday.live","trades",s.trades_total),_metric("intraday.live","instruments",s.instruments_total),_metric("intraday.live","pnl",s.pnl,"MONEY_RUB"),_metric("intraday.live","last_trade",s.last_trade_at,"DATETIME"))
    paper=(_metric("intraday.paper","paper_status",s.paper_status,"DOMAIN_CODE"),_metric("intraday.paper","paper_signals",s.paper_signals_today),_metric("intraday.paper","paper_fills",s.paper_fills_today),_metric("intraday.paper","paper_pnl",s.paper_pnl_today,"MONEY_RUB"))
    shadow=(_metric("intraday.shadow","shadow_orders",s.shadow_orders_total),_metric("intraday.shadow","shadow_fills",s.shadow_fills_total),_metric("intraday.shadow","shadow_positions",s.shadow_positions_total),_metric("intraday.shadow","shadow_last_event",s.shadow_last_event_at,"DATETIME"))
    times=[x for x in (s.last_trade_at,s.paper_refreshed_at,s.shadow_last_event_at) if x]; source=min(times) if times else s.generated_at
    d=RenderDocumentV2(document_id="operator.intraday.v2",locale_code="ru-RU",fallback_locale_code="ru-RU",timezone_code=timezone_code,generated_at=s.generated_at,source_as_of=source,quality_code="MIXED_FRESHNESS",root=RenderNodeV2(RenderNodeTypeV2.WORKSPACE,"workspace.intraday",children=(RenderNodeV2(RenderNodeTypeV2.PAGE,"page.intraday",state=RenderNodeStateV2(status_code="WARNING",quality_code="MIXED_FRESHNESS"),children=(_leaf(RenderNodeTypeV2.TITLE,"intraday.title",key="intraday.workspace.title",level="PAGE"),_leaf(RenderNodeTypeV2.SUBTITLE,"intraday.subtitle",key="intraday.workspace.subtitle"),_section("live","READY" if s.trades_total else "EMPTY",s.last_trade_at,"public.v_intraday_pnl_ru",intraday),_section("paper","WARNING",s.paper_refreshed_at,"marketcore_ui.paper_runtime_summary_v1",paper),_section("shadow","WARNING",s.shadow_last_event_at,"public.shadow_runtime_*",shadow))),)))
    validate_render_document_v2(d);return d
