from __future__ import annotations
from marketcore.presentation.render_tree.v2 import RenderContentV2,RenderDocumentV2,RenderNodeStateV2,RenderNodeTypeV2,RenderNodeV2,validate_render_document_v2
from marketcore.presentation.workspace_v2.domain.program_snapshot_v2 import ProgramSnapshotV2
def _leaf(t,i,*,key=None,value=None,fmt=None,level=None):return RenderNodeV2(t,i,content=RenderContentV2(message_key=key,value=value,format_code=fmt,level_code=level))
def _metric(code,value,fmt="DOMAIN_CODE"):return RenderNodeV2(RenderNodeTypeV2.METRIC_ROW,f"program.metric.{code}",children=(_leaf(RenderNodeTypeV2.METRIC_LABEL,f"program.metric.{code}.label",key=f"program.metric.{code}"),_leaf(RenderNodeTypeV2.METRIC_VALUE,f"program.metric.{code}.value",value=value,fmt=fmt)))
def render_program_domain_v2(s:ProgramSnapshotV2,*,timezone_code="Europe/Moscow"):
    times=[v for v in (s.summary_refreshed_at,s.readiness_refreshed_at) if v];source=min(times) if times else s.generated_at
    summary=(_metric("quarter",s.quarter_code),_metric("platform_status",s.platform_status),_metric("research_status",s.research_status),_metric("top3_status",s.top3_status),_metric("paper_status",s.paper_status),_metric("marketcore_status",s.marketcore_status))
    readiness=(_metric("readiness_total",s.readiness_total,"INTEGER"),_metric("readiness_ready",s.readiness_ready,"INTEGER"),_metric("micro_live_allowed",s.micro_live_allowed,"INTEGER"))
    d=RenderDocumentV2(document_id="operator.program.v2",locale_code="ru-RU",fallback_locale_code="ru-RU",timezone_code=timezone_code,generated_at=s.generated_at,source_as_of=source,quality_code="MIXED_FRESHNESS",root=RenderNodeV2(RenderNodeTypeV2.WORKSPACE,"workspace.program",children=(RenderNodeV2(RenderNodeTypeV2.PAGE,"page.program",state=RenderNodeStateV2(status_code="WARNING",quality_code="MIXED_FRESHNESS"),children=(_leaf(RenderNodeTypeV2.TITLE,"program.title",key="program.workspace.title",level="PAGE"),_leaf(RenderNodeTypeV2.SUBTITLE,"program.subtitle",key="program.workspace.subtitle"),RenderNodeV2(RenderNodeTypeV2.SECTION,"program.section.summary",state=RenderNodeStateV2(status_code="WARNING",freshness_code="STALE",source_as_of=s.summary_refreshed_at,source_identity="marketcore_ui.program_summary_v1"),children=(_leaf(RenderNodeTypeV2.TITLE,"program.section.summary.title",key="program.section.summary.title",level="SECTION"),RenderNodeV2(RenderNodeTypeV2.METRIC_LIST,"program.summary.metrics",children=summary))),RenderNodeV2(RenderNodeTypeV2.SECTION,"program.section.readiness",state=RenderNodeStateV2(status_code="BLOCKED" if s.micro_live_allowed==0 else "WARNING",freshness_code="AS_OF_REPORTED",source_as_of=s.readiness_refreshed_at,source_identity="marketcore_ui.micro_live_readiness_v1"),children=(_leaf(RenderNodeTypeV2.TITLE,"program.section.readiness.title",key="program.section.readiness.title",level="SECTION"),RenderNodeV2(RenderNodeTypeV2.METRIC_LIST,"program.readiness.metrics",children=readiness))))),)))
    validate_render_document_v2(d);return d
