BEGIN;

GRANT CONNECT ON DATABASE finam_core TO alex;
GRANT USAGE ON SCHEMA marketcore_ui TO alex;
GRANT SELECT ON ALL TABLES IN SCHEMA marketcore_ui TO alex;
ALTER DEFAULT PRIVILEGES IN SCHEMA marketcore_ui GRANT SELECT ON TABLES TO alex;

COMMIT;
