
apiVersion: 1

datasources:

  - name: FinamPostgres

    type: postgres

    access: proxy

    url: host.docker.internal:5432

    user: finam

    secureJsonData:

      password: finam

    jsonData:

      database: finam_core

      sslmode: disable

      postgresVersion: 1500

    editable: true

