ALTER TABLE analytics.feature_snapshot_v1
ADD COLUMN IF NOT EXISTS return1_pct NUMERIC(20,8),
ADD COLUMN IF NOT EXISTS return5_pct NUMERIC(20,8),
ADD COLUMN IF NOT EXISTS volume_sma20 NUMERIC(20,4),
ADD COLUMN IF NOT EXISTS volume_ratio20 NUMERIC(20,8);
