BEGIN;

UPDATE analytics.system_job_schedule_v1
SET enabled=false,
    config_version='DISABLED_LEGACY_EXECUTOR_NOT_ALLOWED_V1',
    updated_at=clock_timestamp()
WHERE job_code IN (
    'ARCHIVE_EXACT_V3_BRANCH_PLAN',
    'ARCHIVE_V3_OOS_BRIDGE',
    'INSTRUMENT_DATA_REMEDIATION',
    'TEMPORAL_OOS_BRANCH_GENERATOR',
    'TRADE_OUTCOME_HYPOTHESIS_GENERATOR',
    'TRADE_OUTCOME_OOS_ADMISSION',
    'TRADE_OUTCOME_PATTERN_ANALYSIS'
)
  AND executor_code IN (
    'ARCHIVE_EXACT_V3_BRANCH_PLAN_V1',
    'ARCHIVE_V3_OOS_BRIDGE_V1',
    'INSTRUMENT_DATA_REMEDIATION_V1',
    'TEMPORAL_OOS_BRANCH_GENERATOR_V1',
    'TRADE_OUTCOME_HYPOTHESIS_GENERATOR_V1',
    'TRADE_OUTCOME_OOS_ADMISSION_V1',
    'TRADE_OUTCOME_PATTERN_ANALYSIS_V1'
  );

COMMIT;
