GRANT CONNECT ON DATABASE finam_core TO finam;

GRANT USAGE, CREATE ON SCHEMA analytics TO finam;
GRANT USAGE, CREATE ON SCHEMA presentation TO finam;
GRANT USAGE, CREATE ON SCHEMA marketcore TO finam;
GRANT USAGE, CREATE ON SCHEMA marketcore_ui TO finam;
GRANT USAGE, CREATE ON SCHEMA public TO finam;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA analytics TO finam;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA presentation TO finam;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA marketcore TO finam;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA marketcore_ui TO finam;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO finam;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA analytics TO finam;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA presentation TO finam;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA marketcore TO finam;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA marketcore_ui TO finam;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO finam;

ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT ALL PRIVILEGES ON TABLES TO finam;
ALTER DEFAULT PRIVILEGES IN SCHEMA presentation GRANT ALL PRIVILEGES ON TABLES TO finam;
ALTER DEFAULT PRIVILEGES IN SCHEMA marketcore GRANT ALL PRIVILEGES ON TABLES TO finam;
ALTER DEFAULT PRIVILEGES IN SCHEMA marketcore_ui GRANT ALL PRIVILEGES ON TABLES TO finam;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO finam;

ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT ALL PRIVILEGES ON SEQUENCES TO finam;
ALTER DEFAULT PRIVILEGES IN SCHEMA presentation GRANT ALL PRIVILEGES ON SEQUENCES TO finam;
ALTER DEFAULT PRIVILEGES IN SCHEMA marketcore GRANT ALL PRIVILEGES ON SEQUENCES TO finam;
ALTER DEFAULT PRIVILEGES IN SCHEMA marketcore_ui GRANT ALL PRIVILEGES ON SEQUENCES TO finam;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO finam;
